on:
  push:
    branches:
      - homolog
      - main
      - master
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2